<a href="https://colab.research.google.com/github/sma005/deep-learning-challenge/blob/main/Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# @title Default title text
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
# https://favtutor.com/blogs/pandas-unique-values-in-column
uniqueValues = application_df.nunique()
print(uniqueValues)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
valueCounts = application_df["APPLICATION_TYPE"].value_counts()
valueCounts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = []

for i,j in valueCounts.items():
  if j < 500:
    application_types_to_replace.append(i)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification = application_df["CLASSIFICATION"].value_counts()
classification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#https://stackoverflow.com/questions/67006008/pandas-how-to-get-the-value-counts-above-a-threshold
classification_counts = application_df["CLASSIFICATION"].value_counts(dropna=False)[application_df["CLASSIFICATION"].value_counts(dropna=False) > 1]
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = []

for i,j in classification.items():
  if j < 1000:
    classifications_to_replace.append(i)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [18]:
# Convert categorical data to numeric with `pd.get_dummies`
dummy = pd.get_dummies(application_df)

In [19]:
# Split our preprocessed data into our features and target arrays
X = dummy.drop(['IS_SUCCESSFUL'], axis=1)
y = dummy['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [20]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [22]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 352

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 403 (1.57 KB)
Trainable params: 403 (1.57 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [23]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [24]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6158 - accuracy: 0.6840
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5744 - accuracy: 0.7189
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5657 - accuracy: 0.7251
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5602 - accuracy: 0.7262
Epoch 5/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5571 - accuracy: 0.7273
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5555 - accuracy: 0.7275
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5544 - accuracy: 0.7299
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7303
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5531 - accuracy: 0.7310
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5527 - accuracy: 0.7297
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5520 - accuracy: 0.7294
Epoch 12/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5516 - accuracy: 0.7305
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5515 - accuracy: 0.7298
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5509 - accuracy: 0.7313
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5505 - accuracy: 0.7314
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7310
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7303
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7317
Epoch 19/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5500 - accuracy: 0.7310
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7295
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7318
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7316
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7302
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7318
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7320
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5487 - accuracy: 0.7322
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7325
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7324
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7328
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7327
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7326
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5483 - accuracy: 0.7315
Epoch 33/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5481 - accuracy: 0.7326
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7334
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7318
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7314
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5477 - accuracy: 0.7322
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7311
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5474 - accuracy: 0.7329
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5473 - accuracy: 0.7336
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7326
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7338
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7331
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7310
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7323
Epoch 46/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5469 - accuracy: 0.7339
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7322
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7330
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7335
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7329
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7336
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7338
Epoch 53/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5465 - accuracy: 0.7327
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7335
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7332
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7332
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7335
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7345
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7329
Epoch 60/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5473 - accuracy: 0.7334
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7336
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7336
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7330
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7335
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7348
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7337
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5463 - accuracy: 0.7346
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7338
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7337
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7339
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7344
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7327
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7339
Epoch 74/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5460 - accuracy: 0.7345
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7348
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7337
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7339
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7341
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7352
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7354
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7339
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7346
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7346
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7345
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7343
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7341
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7342
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5461 - accuracy: 0.7337
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7329
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7346
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7336
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7339
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7345
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7351
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7347
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7349
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7346
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7343
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7340
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7332

In [25]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5545 - accuracy: 0.7286 - 504ms/epoch - 2ms/step
Loss: 0.5544688701629639, Accuracy: 0.7286297082901001

In [26]:
# Export our model to HDF5 file
nn.save_weights('nn_model.hdf5')